obj-m += crypto-core.o

all:

	make -C /home/alberto/Desktop/os/qemu/buildroot/output/build/linux-6.1.44/ M=$(PWD) modules

clean:

	make -C /home/alberto/Desktop/os/qemu/buildroot/output/build/linux-6.1.44/ M=$(PWD) clean
